name: EasyDesk Microservice Build Job
description: >
  Builds and tests a .NET microservice and produces an SQL script to update
  the associated database.

branding:
  color: green
  icon: check

inputs:
  dotnet-version:
    description: The dotnet version to be used.
    required: true
  main-project:
    description: The path to the main project.
    required: true
  unit-tests-project:
    description: The path to the unit test project.
    required: true
  output-dir:
    description: The name of the directory where the build output will be stored (defaults to 'out/app').
    required: false
    default: out/app    
  sql-file-name:
    description: The name of the generated SQL script (defaults to 'out/update-database.sql').
    required: false
    default: out/update-database.sql
  warnings-as-errors:
    description: Whether to treat build warnings as errors.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Build
      uses: EasyDesk/action-dotnet-build@v1
      with:
        warnings-as-errors: ${{ inputs.warnings-as-errors }}
    - name: Run Unit Tests
      uses: EasyDesk/action-dotnet-test@v1
      with:
        path: ${{ inputs.unit-tests-project }}
    - name: Generate database script
      uses: EasyDesk/action-generate-migrations-script@v1
      with:
        project-dir: ${{ inputs.main-project }}
        output-file: ${{ inputs.sql-file-name }}
    - name: Publish
      uses: EasyDesk/action-dotnet-publish@v1
      with:
        path: ${{ inputs.main-project }}
        output-dir: ${{ inputs.binaries-dir }}
